# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('HP', models.FloatField(default=0)),
                ('job_number', models.CharField(max_length=200)),
                ('volume', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('image', models.ImageField(upload_to='images')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='giliyal.detail')),
            ],
        ),
    ]
